### ISSUE TITLE
ERA 5 Wave Spectra

### ISSUE THREAD

**Issue by sebfournier95** [ecmwf/cdsapi#59]
Hello

What is the most recent data available ? 

In fact from a date how long do I have to wait to have the data reanalyzed ?

**Comment by sebfournier95** [comment]
Steps to Reproduce

import cdsapi
import os
import sys
import shutil
import glob
import subprocess as sp
import numpy as np
import datetime
import urllib3

# Hour is in UTC convention

# Different tools to download ERA5 datas which are re-analysis datas from ECMWF
class ERA5_Tools:
    def __init__(self, race_name='TEST', north_coord=52, west_coord=-75, south_coord=10, east_coord=0):
        self.race_name = race_name

        # Convention: [N(positif), W(negatif), S(negatif), E(positif)]

        self.north_coord = north_coord
        self.west_coord = west_coord
        self.east_coord = east_coord
        self.south_coord = south_coord

        self.area = [north_coord, west_coord, south_coord, east_coord]

    # Download wave spectra for several days
    def ERA5_Wave_Spectra_Several_Days_TMP(self, day_list, month, year, archive_path='F:\\GRIBS\\ECMWF\\WAVE_SPECTRA\\'):
        if os.path.isdir(archive_path) is False:
            os.mkdir(archive_path)

        date_str = str()

        for day in day_list:
            date = str(day) + '/' + str(month) + '/' + str(year) + ' - ' + str(0) + ':' + str(0) + ':' + str(0)

            # convert string to datetimeformat
            date = datetime.datetime.strptime(date, "%d/%m/%Y - %H:%M:%S")
            date_name = date.strftime('%Y-%m-%d')

            date_str += date_name

        date_str = date_str.replace(str(day_list[0]), str(day_list[0]) + '/')

        name = self.race_name + '.grib'

        c = cdsapi.Client()

        c.retrieve('reanalysis-era5-complete', {
            'class': 'ea',
            'date': date_str,
            'time': '00:00:00/01:00:00/02:00:00/03:00:00/04:00:00/05:00:00/06:00:00/07:00:00/08:00:00/09:00:00/10:00:00/11:00:00/12:00:00/13:00:00/14:00:00/15:00:00/16:00:00/17:00:00/18:00:00/19:00:00/20:00:00/21:00:00/22:00:00/23:00:00',
            'direction': '1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/16/17/18/19/20/21/22/23/24',
            'domain': 'g',
            'expver': '1',
            'frequency': '1/2/3/4/5/6/7/8/9/10/11/12/13/14/15/16/17/18/19/20/21/22/23/24/25/26/27/28/29/30',
            'param': '251.140',
            'stream': 'wave',
            'area': self.area,
            'type': 'an',
            'format': 'grib',
            'grid': '0.5/0.5',
        }, name)

        shutil.copy(name, archive_path + name)
        os.remove(name)

Offshore_2 = ERA5_Tools(race_name='Offshore_2', north_coord=52, west_coord=-13, south_coord=43, east_coord=0)
Offshore_2.ERA5_Wave_Spectra_Several_Days_TMP([11, 12], 6, 2022, archive_path='F:\\GRIBS\\ECMWF\\WAVE_SPECTRA\\')

**Comment by sebfournier95** [comment]
Error : 

2022-06-24 11:55:46,935 INFO Welcome to the CDS
2022-06-24 11:55:46,935 INFO Sending request to https://cds.climate.copernicus.eu/api/v2/resources/reanalysis-era5-complete
2022-06-24 11:55:47,005 INFO Request is queued
2022-06-24 11:55:48,073 INFO Request is running
2022-06-24 12:02:06,649 INFO Request is failed
2022-06-24 12:02:06,649 ERROR Message: the request you have submitted is not valid
2022-06-24 12:02:06,649 ERROR Reason:  Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Expected 17280, got 0.; Could not find a MARS database to perform request; Request failed; Some errors reported (last error -2)
2022-06-24 12:02:06,649 ERROR   Traceback (most recent call last):
2022-06-24 12:02:06,649 ERROR     File "/opt/cdstoolbox/cdscompute/cdscompute/cdshandlers/services/handler.py", line 59, in handle_request
2022-06-24 12:02:06,649 ERROR       result = cached(context.method, proc, context, context.args, context.kwargs)
2022-06-24 12:02:06,649 ERROR     File "/opt/cdstoolbox/cdscompute/cdscompute/caching.py", line 108, in cached
2022-06-24 12:02:06,649 ERROR       result = proc(context, *context.args, **context.kwargs)
2022-06-24 12:02:06,650 ERROR     File "/opt/cdstoolbox/cdscompute/cdscompute/services.py", line 124, in __call__
2022-06-24 12:02:06,650 ERROR       return p(*args, **kwargs)
2022-06-24 12:02:06,650 ERROR     File "/opt/cdstoolbox/cdscompute/cdscompute/services.py", line 60, in __call__
2022-06-24 12:02:06,650 ERROR       return self.proc(context, *args, **kwargs)
2022-06-24 12:02:06,650 ERROR     File "/home/cds/cdsservices/services/mars/mars.py", line 52, in external
2022-06-24 12:02:06,650 ERROR       return mars(context, request, **kwargs)
2022-06-24 12:02:06,650 ERROR     File "/home/cds/cdsservices/services/mars/mars.py", line 19, in mars
2022-06-24 12:02:06,650 ERROR       execute_mars(context, requests)
2022-06-24 12:02:06,650 ERROR     File "/home/cds/cdsservices/services/mars/execute_mars.py", line 18, in execute_mars
2022-06-24 12:02:06,650 ERROR       context.run_command("/usr/local/bin/mars", tmp, exception=MarsException)
2022-06-24 12:02:06,650 ERROR     File "/opt/cdstoolbox/cdscompute/cdscompute/context.py", line 209, in run_command
2022-06-24 12:02:06,650 ERROR       raise exception(call, proc.returncode, output)
2022-06-24 12:02:06,650 ERROR   home.cds.cdsservices.services.mars.__init__.py.exceptions.MarsException: Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Expected 17280, got 0.; Could not find a MARS database to perform request; Request failed; Some errors reported (last error -2)
Traceback (most recent call last):
  File "C:/Users/Seb/PycharmProjects/RTools/weather_tools.py", line 745, in <module>
    Intens.ERA5_Wave_Spectra_Several_Days_TMP([5, 6], 5, 2022, archive_path='F:\\GRIBS\\ECMWF\\WAVE_SPECTRA\\Intens\\')
  File "C:/Users/Seb/PycharmProjects/RTools/weather_tools.py", line 481, in ERA5_Wave_Spectra_Several_Days_TMP
    c.retrieve('reanalysis-era5-complete', {
  File "C:\Users\Seb\anaconda3\envs\routing\lib\site-packages\cdsapi\api.py", line 348, in retrieve
    result = self._api("%s/resources/%s" % (self.url, name), request, "POST")
  File "C:\Users\Seb\anaconda3\envs\routing\lib\site-packages\cdsapi\api.py", line 506, in _api
    raise Exception(
Exception: the request you have submitted is not valid. Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Failed to read 1 (Connection reset by peer); Bad tag '0' (should be 'unsigned long long'); Failed to read 4 (Connection reset by peer); Failed to read 4 (Connection reset by peer); Expected 17280, got 0.; Could not find a MARS database to perform request; Request failed; Some errors reported (last error -2).

Process finished with exit code 1

**Comment by EddyCMWF** [comment]
Hi @sebfournier95 ,
The failure here is because you have made a request that isn't valid. This is not an issue with the cdsapi software so I recommend that you request help from the CDS user support channel:
https://cds.climate.copernicus.eu/cdsapp#!/usersupport
They will help you with queries regarding the availability of data and issues regarding valid requests.
Many thanks,
Eddy
